services:
  - type: web
    name: school-attendance
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: SMS_TOKEN
        sync: false
